version: '3.8'

services:
  # Test Database
  postgres_test:
    image: postgres:latest

    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:latest
    ports:
      - '6666:6379'

volumes:
  postgres_test_data:
