version: '3.8'

services:
  # Test Database
  postgres_test:
    image: postgres:latest
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}_test
    volumes:
      - ./erd.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_test_data:
