const currencyKoreanNameMapper: { [code: string]: string } = {
  USD: '미국 달러',
  EUR: '유로',
  JPY: '일본 엔',
  GBP: '영국 파운드',
  AUD: '호주 달러',
  CAD: '캐나다 달러',
  CHF: '스위스 프랑',
  CNY: '중국 위안',
  HKD: '홍콩 달러',
  SGD: '싱가포르 달러',
  KRW: '한국 원',
  BRL: '브라질 레알',
  RUB: '러시아 루블',
  INR: '인도 루피',
  MXN: '멕시코 페소',
  SAR: '사우디아라비아 리얄',
  AED: '아랍에미리트 디르함',
  TRY: '터키 리라',
  ZAR: '남아프리카 랜드',
  SEK: '스웨덴 크로나',
  NOK: '노르웨이 크로네',
  DKK: '덴마크 크로네',
  PLN: '폴란드 즈워티',
  IDR: '인도네시아 루피아',
  THB: '태국 밧',
  MYR: '말레이시아 링깃',
  PHP: '필리핀 페소',
  NZD: '뉴질랜드 달러',
  ILS: '이스라엘 신권',
  TWD: '대만 달러',
  CLP: '칠레 페소',
  COP: '콜롬비아 페소',
  PEN: '페루 솔',
  ARS: '아르헨티나 페소',
  CZK: '체코 코루나',
  HUF: '헝가리 포린트',
  HRK: '크로아티아 쿠나',
  ISK: '아이슬란드 크로나',
  RON: '루마니아 레우',
  BGN: '불가리아 레프',
  EGP: '이집트 파운드',
  MAD: '모로코 디르함',
  QAR: '카타르 리얄',
  KWD: '쿠웨이트 디나르',
  BHD: '바레인 디나르',
  OMR: '오만 리얄',
  JOD: '요르단 디나르',
  LBP: '레바논 파운드',
  EEK: '에스토니아 크룬',
  LTL: '리투아니아 리타스',
  LVL: '라트비아 라트',
  MKD: '마케도니아 데나르',
  MDL: '몰도바 레우',
  RSD: '세르비아 디나르',
  UAH: '우크라이나 그리브나',
  BYR: '벨라루스 루블',
  KZT: '카자흐스탄 텡게',
  UZS: '우즈베키스탄 숨',
  AZN: '아제르바이잔 마나트',
  GEL: '조지아 라리',
  AMD: '아르메니아 드람',
  IRR: '이란 리얄',
  AFN: '아프가니스탄 아프가니',
  PKR: '파키스탄 루피',
  BDT: '방글라데시 타카',
  LKR: '스리랑카 루피',
  NPR: '네팔 루피',
  MVR: '몰디브 루피아',
  KHR: '캄보디아 리엘',
  VND: '베트남 동',
  MMK: '미얀마 키얏',
  LAK: '라오스 킵',
  MNT: '몽골 투그릭',
  CRC: '코스타리카 콜론',
  PAB: '파나마 발보아',
  DOP: '도미니카 공화국 페소',
  GTQ: '과테말라 케찰',
  HNL: '온두라스 렘피라',
  NIO: '니카라과 코르도바',
  PYG: '파라과이 과라니',
  SVC: '엘살바도르 콜론',
  UYU: '우루과이 페소',
  BBD: '바베이도스 달러',
  BZD: '벨리즈 달러',
  JMD: '자메이카 달러',
  TTD: '트리니다드 토바고 달러',
  BSD: '바하마 달러',
  GYD: '가이아나 달러',
  SRD: '수리남 달러',
  XCD: '동카리브해 달러',
  XAF: '중앙아프리카 CFA 프랑',
  XOF: '서아프리카 CFA 프랑',
  MGA: '마다가스카르 아리아리',
  RWF: '르완다 프랑',
  SCR: '세이셀 루피',
  AOA: '앙골라 콴자',
  BWP: '보츠와나 풀라',
  NAD: '나미비아 달러',
  ZMK: '잠비아 콰차',
  SZL: '스와질란드 릴랑게니',
  LSL: '레소토 로티',
  MUR: '모리셔스 루피',
  KES: '케냐 실링',
  UGX: '우간다 실링',
  TZS: '탄자니아 실링',
  GHS: '가나 세디',
  NGN: '나이지리아 나이라',
  SLL: '시에라리온 리온',
  LRD: '라이베리아 달러',
  SOS: '소말리아 실링',
  ETB: '에티오피아 비르',
  DZD: '알제리 디나르',
  TND: '튀니지 디나르',
  LYD: '리비아 디나르',
  CDF: '콩고 프랑',
  GNF: '기니 프랑',
  XPF: '태평양 프랑',
  XAG: '은화',
  XAU: '금화',
};

export function getCurrencyNameInKorean(code: string): string {
  const koreanName = currencyKoreanNameMapper[code.toUpperCase()];

  return koreanName;
}
