name: Exchange Watch Backend Deploy (Production)

on:
  push:
    branches: [ main ]
    paths: 
      - '**'
      - '!test/**'
      - '!**/*.spec.ts'
      - '!**/*.test.ts'
      - '!**/*.md'
      - '!.github/**'
      - '!.eslintrc*'
      - '!.prettierrc*'
      - '!jest.config*'
      - '!coverage/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    
    - name: Build and push Docker image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: exchange-watch-backend
        IMAGE_TAG: ${{ github.sha }}
      run: |
        echo "Building Docker image..."
        docker build -f Dockerfile.prod -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
        
        echo "Pushing to ECR..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.1.0
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: exchange-watch-backend
        IMAGE_TAG: ${{ github.sha }}
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        timeout: 600s
        envs: ECR_REGISTRY,ECR_REPOSITORY,IMAGE_TAG
        script: |
          cd ~/exchangeWatch
          
          echo "Login to ECR..."
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin $ECR_REGISTRY
          
          echo "Pulling new image..."
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          
          echo "Starting Blue-Green deployment"
          
          # 현재 색상 확인
          BLUE_RUNNING=$(docker ps --filter "name=exchangewatch-blue" --format "{{.Names}}" | wc -l)
          
          if [ $BLUE_RUNNING -gt 0 ]; then
            CURRENT_COLOR="blue"
            NEW_COLOR="green"
          else
            CURRENT_COLOR="green"
            NEW_COLOR="blue"
          fi
          
          echo "Current active: $CURRENT_COLOR → Deploying: $NEW_COLOR"
          
          NEW_CONTAINER_PREFIX="exchangewatch-${NEW_COLOR}"
          OLD_CONTAINER_PREFIX="exchangewatch-${CURRENT_COLOR}"
          
          # 새 버전 컨테이너 시작 (1개 카나리)
          echo "Starting $NEW_COLOR canary container..."
          if [ "$NEW_COLOR" = "green" ]; then
            GREEN_IMAGE=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG docker-compose up -d --no-deps green
          else
            BLUE_IMAGE=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG docker-compose up -d --no-deps blue
          fi
          
          # 헬스체크
          echo "Health checking $NEW_COLOR..."
          sleep 20
          
          if ! docker exec exchangewatch-nginx-1 curl -f -s http://$NEW_COLOR:3000/api/health > /dev/null 2>&1; then
            echo "$NEW_COLOR health check failed. Aborting deployment."
            docker-compose stop $NEW_COLOR
            exit 1
          fi
          echo "$NEW_COLOR is healthy!"
          
          # nginx 포트 포워딩 변경 및
          echo "Switching nginx traffic to $NEW_COLOR..."
          sed -i "s/server ${CURRENT_COLOR}:3000/server ${NEW_COLOR}:3000/g" nginx/nginx.conf
          docker-compose restart nginx
          
          # 구버전 컨테이너 종료
          echo "Stopping old $CURRENT_COLOR containers..."
          docker-compose stop $CURRENT_COLOR
          
          # 신버전을 3개로 확장
          echo "Scaling $NEW_COLOR to ${CURRENT_SCALE:-3} instances..."
          if [ "$NEW_COLOR" = "green" ]; then
            GREEN_IMAGE=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG docker-compose up -d --scale green=${CURRENT_SCALE:-3} --no-recreate
          else
            BLUE_IMAGE=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG docker-compose up -d --scale blue=${CURRENT_SCALE:-3} --no-recreate
          fi
          
          echo "Blue-Green deployment completed successfully!"
          echo "Active containers: $NEW_COLOR (${CURRENT_SCALE:-3} instances)"
          echo "Image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          
          echo "Cleaning up old images..."
          docker image prune -f
          
          echo "Deployment completed"
