name: PR test for protect develop branch
on:
    pull_request:
      branches: [develop]

jobs:
    test:
      runs-on: ubuntu-latest

      services:
        postgres:
          image: postgres:latest
          env:
            POSTGRES_PASSWORD: test
            POSTGRES_USER: test
            POSTGRES_DB: exchange_watch_test
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
          ports:
            - 5432:5432

        redis:
          image: redis:7-alpine
          options: >-
            --health-cmd "redis-cli ping"
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
          ports:
            - 6379:6379

      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: '23'
            cache: 'npm'

        - name: Install & Build
          run: |
            npm ci
            npm run build

        - name: Run Unit Tests
          run: npm run test:unit

        - name: Create .env.test file for GitHub Actions
          run: |
            cat > .env.test << EOF
            NODE_ENV=test
            DATABASE_URL=postgresql://test:test@localhost:5432/exchange_watch_test
            POSTGRES_USER=test
            POSTGRES_PASSWORD=test
            POSTGRES_DB=exchange_watch_test
            REDIS_HOST=localhost
            REDIS_PORT=6379
            REDIS_PASSWORD=
            JWT_ACCESS_SECRET=test-jwt-access-secret-key-for-integration-tests
            JWT_REFRESH_SECRET=test-jwt-refresh-secret-key-for-integration-tests
            GOOGLE_CLIENT_ID=test-google-client-id
            GOOGLE_CLIENT_SECRET=test-google-client-secret
            OPENAI_API_KEY=test-openai-api-key
            COIN_API_KEY=test-coin-api-key
            CURRENCY_LAYER_API_KEY=test-currency-layer-api-key
            FIXER_API_KEY=test-fixer-api-key
            EOF

        - name: Run Integration Tests
          run: npm run test:integration

        - name: Health Check
          run: |
            npm run start:prod &
            sleep 15
            curl -f http://localhost:3000/api/health
